### ISSUE TITLE
Crash in ROI cleanup

### ISSUE THREAD

**Issue by chrisadamsonmcri** [LupoLab-UCSF/CMB_labeler#2]
>> cmb_detection('test_swi.nii', pwd, 'diagoff', 'semion');
Scaling the intensity of SWI...
Compute 2D Fast Radial Symmetry Transform...
Start 3D region growing and geometric feature examination...
Starting volume segmentation...
Beginning clean up of segmentation results...
ROI #1/336
Error:File: imagine.m Line: 195 Column: 31
Identifier 'SSaveVar' is not a function or a shared variable. To share 'SSaveVar' with nested function, initialize it
in the current scope. For more information, see Sharing Variables Between Parent and Nested Functions.

Error in cmbevaluation2

Error in cmb_detection

**Comment by mmorri10** [comment]
Thank you for notifying us and our apologizes for not responding sooner. The GUI (imagine) file appeared to be corrupted. This has been fixed.

**Comment by gmadevs** [comment]
I have the same issue even with the updated file you committed! Do you know if it's a known issue with new versions of MATLAB?

Thank you!

GMA

**Comment by ahmedhumza94** [comment]
I have this issue with matlab 2020b. Seem to be able to get past this with an older version (2017b).
